config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :replies
  end

  devise_for :users
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :replies

  validates :title, presence: :true
  validates :content, presence: :true
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :content, presence: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "New post created"
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @reply = Reply.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @reply = Reply.new
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @reply = Reply.new(reply_params)
    @reply.post_id = @post.id
    @reply.user_id = current_user.id
    if @reply.save
      flash[:notice] = "New reply created"
      redirect_to post_path(@reply.post_id)
    else
      render :new
    end
  end

  def show
    @reply = Reply.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  private

  def reply_params
    params.require(:reply).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Homepage</h1>

<% if user_signed_in? %>
  <p>You are logged in as: <%= current_user.email %>.</p>
  <p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
<% else %>
  <p><%= link_to "Sign Up", new_user_registration_path %></p>
  <p><%= link_to "Sign In", new_user_session_path %></p>
<% end %>

<h3>Go to the <%= link_to "Message Board", posts_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/posts">Message Board</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="navbar-text"><%= current_user.email %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div class="btn btn-primary pull-right"><%= link_to "Create a new post", new_post_path %></div>

<table class="table table-hover">
  <thead>
    <th>Title</th>
    <th>Author</th>
    <th>Date Posted</th>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to "#{post.title}", post_path(post) %></td>
        <td><%= post.user.email %></td>
        <td><%= post.updated_at.strftime("%B %-d, %Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <br>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, size: "60x12" %>
  </div>
  <%= f.submit "Create" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Posted by: <strong><%= @post.user.email %></strong> on <%= @post.updated_at.strftime("%B %-d, %Y at %H:%M") %></p>
<p><%= @post.content %></p>
<hr>
<h2>Replies</h2>
<% @post.replies.each do |reply| %>
  <p><%= reply.content %></p>
  <p>-- <%= reply.user.email %> on <%= reply.updated_at.strftime("%B %-d, %Y at %H:%M") %></p>
  <br>
<% end %>

<h3>New Reply</h3>
<%= form_for [@post, @reply], url: post_replies_path(@post) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, size: "60x12" %>
  </div>
  <%= f.submit "Reply" %>
<% end %>

app/views/replies/new.html.erb
<h1>Replying to <em><%= @post.title %></em></h1>

<%= form_for @reply, url: post_replies_path do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, size: "60x12" %>
  </div>
  <%= f.submit "Reply" %>
<% end %>

app/views/replies/show.html.erb
<h1>In response to <em><%= @post.title %></em></h1>
<p>Posted by: <%= @reply.user.email %></p>
<p>on <%= @reply.updated_at %></p>
<hr>
<p><%= @reply.content %></p>
<hr>
<p><%= link_to "Go to Post", post_path(@reply.post_id) %></p>